@startuml
title System Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь умного дома")
Person(admin, "Administrator", "Администратор управляющий системой")

System(SmartHome, "SmartHome System", "Монолитная система управления умным домом")

System_Ext(client1, "Connected home 1", "Подключенный дом к системе")
System_Ext(client2, "Connected home N", "Подключенный дом к системе")

Rel(user, SmartHome, "Настройка устройств и просмотр информации")
Rel(admin, SmartHome, "Администрирование системы")

Rel(SmartHome, client1, "Запрос информации с датчиков")
Rel(SmartHome, client2, "Запрос информации с датчиков")

@enduml